/// @version fmh [7c6f0fef29] 2010-10-06 15:54:29
/// @note generated by fmh -infile "C:\rev\src\rpw.core\manifest" -prefix "RPW_CORE_"

#pragma once

#ifndef RPW_CORE_MANIFEST_DATE
#define RPW_CORE_MANIFEST_DATE "2011-05-04 04:22:21.123"
#endif
