/// @version fmh [7c6f0fef29] 2010-10-06 15:54:29
/// @note generated by fmh -infile "C:\rev\src\rpw.core\manifest.uuid" -prefix "RPW_CORE_"

#pragma once

#ifndef RPW_CORE_MANIFEST_UUID
#define RPW_CORE_MANIFEST_UUID "e5a1d05ea4d67dcf7f91009dcf39cdf621835c2b"
#endif

#ifndef RPW_CORE_MANIFEST_VERSION
#define RPW_CORE_MANIFEST_VERSION "e5a1d05ea4"
#endif
